export const SARAPAN_FETCH_MENUS = 'sarapan/fetchMenus'
export const AYAM_FETCH_MENUS = 'ayam/fetchMenus'
export const IKAN_FETCH_MENUS = 'ikan/fetchMenus'
export const SAPI_FETCH_MENUS = 'sapi/fetchMenus'
export const MINUMAN_FETCH_MENUS = 'minuman/fetchMenus'
export const FETCH_MENU = 'menu/fetchDetail'